# Generated by Django 3.2.16 on 2023-04-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='course',
        ),
        migrations.AddField(
            model_name='timetable',
            name='courses',
            field=models.ManyToManyField(null=True, to='timetables.CourseDetail'),
        ),
    ]
