# Generated by Django 3.2.16 on 2023-04-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_auto_20230408_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
