# Generated by Django 3.2.16 on 2023-05-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0003_timetable_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='is_default',
            field=models.BooleanField(),
        ),
    ]
