# Generated by Django 3.2.16 on 2023-04-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_account_profile_friends_+', to='account.Profile'),
        ),
    ]
