version: '3'
services:

  web:
    container_name: web
    #작성
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn django_rest_framework_17th.wsgi:application --bind 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: django_rest_framework_17th.settings.prod
    env_file:
      - django_rest_framework_17th/.env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
        - 8000

    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh

  nginx:
    container_name: nginx
    build : ./config/nginx

    ports :
      - "80:80"

    #작성
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media

    depends_on:
      - web

volumes:
  static:
  media: