version: '3' # 버전 명시 필수
services: # container 이름들 작성

  web:
    container_name: web
    build: # 빌드할 Dockerfile
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn django_rest_framework_17th.wsgi:application --bind 0.0.0.0:8000 # container 가 실행될 때 수행할 명령어
    environment: # 환경 설정
      DJANGO_SETTINGS_MODULE: django_rest_framework_17th.settings.prod
    env_file: # 환경 변수 파일 설정
        - .env.prod
    expose: # container 포트 번호
      - 8000
    volumes: # 데이터 볼륨 매핑
      - static:/home/app/web/static
      - media:/home/app/web/media
    entrypoint: # container 가 실행될 때 '반드시' 실행 되는 명령어
      - sh
      - config/docker/entrypoint.prod.sh

  nginx:
    container_name: nginx
    build: ./config/nginx # 여기에 nginx 에 대한 Dockerfile 이 존재, nginx 에 대한 상위 설정 파일인 nginx.conf 도 있음
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "80:80" # 포트포워딩 (Host 포트 번호 : Container 포트 번호)
    depends_on: # container 생성 순서 규정 (먼저 생성되어야 하는 container 명시)
      - web

volumes:
  static:
  media: