# Generated by Django 3.2.16 on 2023-04-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230402_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takelecture',
            name='profile',
        ),
        migrations.AddField(
            model_name='takelecture',
            name='timeTable',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.timetable'),
        ),
    ]
