# Generated by Django 3.2.16 on 2023-05-05 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0003_auto_20230504_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturereview',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='reviewlike',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='profile',
        ),
        migrations.AddField(
            model_name='lecturereview',
            name='myUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewlike',
            name='myUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='myUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='myUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
