# Generated by Django 3.2.16 on 2023-03-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_board_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blackcomment',
            old_name='writer',
            new_name='who',
        ),
        migrations.RenameField(
            model_name='blackpost',
            old_name='writer',
            new_name='who',
        ),
        migrations.RenameField(
            model_name='likecomment',
            old_name='writer',
            new_name='who',
        ),
        migrations.RenameField(
            model_name='likepost',
            old_name='writer',
            new_name='who',
        ),
        migrations.RenameField(
            model_name='scrappost',
            old_name='writer',
            new_name='who',
        ),
    ]
