# Generated by Django 3.2.16 on 2023-03-31 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20230331_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ancestor_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='board.comment'),
        ),
    ]
